import { createClient } from '@libsql/client';
const c = createClient({ url: 'file:./dev.db' });

// Get listing IDs by brand+model+year
const rows = await c.execute('SELECT id, brand, model, year FROM listings');
const find = (brand, model, year) => rows.rows.find(r => r.brand === brand && r.model === model && r.year === year)?.id;

const specs = [
  {
    id: find('Citroën', 'C4', 2011),
    condition: 'Used, accident-free',
    series: 'B7',
    equipmentLine: 'Exclusive',
    engineDisplacement: 1560,
    performanceKw: 68,
    performanceHp: 92,
    driveType: 'Internal combustion',
    fuelConsumption: '5.8 l/100km',
    co2Emissions: 152,
    cylinders: 4,
    tankSize: 60,
    firstRegistration: '06/2011',
    numberOfOwners: 2,
    huStatus: 'Valid 2026',
    airConditioning: 'Air conditioning',
    parkingAssistance: 'Rear',
    airbags: 'Front, side and curtain airbags',
    colorManufacturer: 'PERLA NERA BLACK',
    interior: 'Cloth, grey',
    vehicleWeight: 1340,
    lastMaintenanceDate: '03/2024',
    lastServiceKm: 196000,
    doors: 5, seats: 5,
  },
  {
    id: find('Dacia', 'Sandero', 2024),
    condition: 'Used, accident-free',
    series: 'B52',
    equipmentLine: 'Expression',
    engineDisplacement: 999,
    performanceKw: 67,
    performanceHp: 91,
    driveType: 'Internal combustion',
    fuelConsumption: '5.6 l/100km',
    co2Emissions: 128,
    cylinders: 3,
    tankSize: 50,
    firstRegistration: '01/2024',
    numberOfOwners: 1,
    huStatus: 'New',
    airConditioning: 'Air conditioning',
    parkingAssistance: 'Rear radar',
    airbags: 'Front and side airbags',
    colorManufacturer: 'GRIS COMETE',
    interior: 'Cloth, dark grey',
    vehicleWeight: 1086,
    lastMaintenanceDate: '10/2024',
    lastServiceKm: 55000,
    doors: 5, seats: 5,
  },
  {
    id: find('Toyota', 'Yaris', 2023),
    condition: 'Used, accident-free',
    series: 'XP210',
    equipmentLine: 'GR Sport',
    engineDisplacement: 1490,
    performanceKw: 85,
    performanceHp: 116,
    driveType: 'Hybrid (petrol + electric)',
    fuelConsumption: '3.8 l/100km',
    co2Emissions: 86,
    cylinders: 3,
    tankSize: 36,
    firstRegistration: '04/2023',
    numberOfOwners: 1,
    huStatus: 'New',
    airConditioning: 'Automatic dual-zone climate control',
    parkingAssistance: 'Front and rear with camera',
    airbags: 'Front, side, curtain and knee airbags',
    colorManufacturer: 'GRIS FONCÉ MÉTALLISÉ',
    color: 'Gris Foncé',
    interior: 'Cloth/alcantara, black',
    vehicleWeight: 1220,
    lastMaintenanceDate: '01/2025',
    lastServiceKm: 50000,
    doors: 5, seats: 5,
  },
  {
    id: find('Peugeot', '3008', 2017),
    condition: 'Used, accident-free',
    series: 'P84',
    equipmentLine: 'Allure',
    engineDisplacement: 1997,
    performanceKw: 110,
    performanceHp: 150,
    driveType: 'Internal combustion',
    fuelConsumption: '6.2 l/100km',
    co2Emissions: 164,
    cylinders: 4,
    tankSize: 53,
    firstRegistration: '12/2017',
    numberOfOwners: 1,
    huStatus: 'Valid 2026',
    airConditioning: 'Automatic climate control',
    parkingAssistance: 'Front and rear with camera 360°',
    airbags: 'Front, side and curtain airbags',
    colorManufacturer: 'GRIS PLATINIUM',
    interior: 'Partial leather, black',
    brakedTrailerLoad: 1800,
    unbrakedTowingCapacity: 750,
    vehicleWeight: 1544,
    lastMaintenanceDate: '11/2024',
    lastServiceKm: 108000,
    doors: 5, seats: 5,
  },
  {
    id: find('Audi', 'A3', 2015),
    condition: 'Used, 2nd owner',
    series: '8V',
    equipmentLine: 'Prestige',
    engineDisplacement: 1598,
    performanceKw: 77,
    performanceHp: 105,
    driveType: 'Internal combustion',
    fuelConsumption: '4.3 l/100km',
    co2Emissions: 113,
    cylinders: 4,
    tankSize: 50,
    firstRegistration: '03/2015',
    numberOfOwners: 2,
    huStatus: 'Valid 2025',
    airConditioning: 'Automatic climate control',
    parkingAssistance: 'Rear',
    airbags: 'Front, side and curtain airbags',
    colorManufacturer: 'IBIS WHITE',
    interior: 'Cloth, black',
    vehicleWeight: 1355,
    lastMaintenanceDate: '09/2024',
    lastServiceKm: 208000,
    doors: 4, seats: 5,
    bodyType: 'Berline',
  },
  {
    id: find('Hyundai', 'Tucson', 2025),
    condition: 'Used, accident-free',
    series: 'NX4',
    equipmentLine: 'N-Line',
    engineDisplacement: 1999,
    performanceKw: 136,
    performanceHp: 185,
    driveType: 'Internal combustion',
    fuelConsumption: '6.9 l/100km',
    co2Emissions: 181,
    cylinders: 4,
    tankSize: 54,
    firstRegistration: '09/2024',
    numberOfOwners: 1,
    huStatus: 'New',
    airConditioning: 'Dual-zone automatic climate control',
    parkingAssistance: 'Front, rear and 360° surround camera',
    airbags: 'Front, side, curtain and driver knee airbags',
    colorManufacturer: 'PHANTOM BLACK',
    interior: 'Leather, black',
    brakedTrailerLoad: 1650,
    vehicleWeight: 1756,
    lastMaintenanceDate: '04/2025',
    lastServiceKm: 85000,
    doors: 5, seats: 5,
    bodyType: 'SUV',
  },
  {
    id: find('Dacia', 'Duster', 2021),
    condition: 'Used, accident-free',
    series: 'HM',
    equipmentLine: 'Essentiel',
    engineDisplacement: 1461,
    performanceKw: 81,
    performanceHp: 110,
    driveType: 'Internal combustion',
    fuelConsumption: '5.5 l/100km',
    co2Emissions: 143,
    cylinders: 4,
    tankSize: 50,
    firstRegistration: '05/2021',
    numberOfOwners: 1,
    huStatus: 'Valid 2026',
    airConditioning: 'Air conditioning',
    parkingAssistance: 'Rear radar',
    airbags: 'Front and side airbags',
    colorManufacturer: 'GRIS HIGHLAND',
    interior: 'Cloth, dark grey',
    brakedTrailerLoad: 1500,
    unbrakedTowingCapacity: 730,
    vehicleWeight: 1410,
    lastMaintenanceDate: '02/2025',
    lastServiceKm: 105000,
    doors: 5, seats: 5,
  },
  {
    id: find('BMW', 'Série 3', 2022),
    condition: 'Used, accident-free',
    series: 'G20',
    equipmentLine: 'Sport Line',
    engineDisplacement: 1995,
    performanceKw: 110,
    performanceHp: 150,
    driveType: 'Internal combustion',
    fuelConsumption: '5.1 l/100km',
    co2Emissions: 134,
    cylinders: 4,
    tankSize: 59,
    firstRegistration: '03/2022',
    numberOfOwners: 1,
    huStatus: 'New',
    airConditioning: 'Automatic dual-zone climate control',
    parkingAssistance: 'Front and rear with surround camera',
    airbags: 'Front, side, curtain and knee airbags',
    colorManufacturer: 'MINERAL WHITE METALLIC',
    interior: 'Leather, black Vernasca',
    brakedTrailerLoad: 1800,
    unbrakedTowingCapacity: 750,
    vehicleWeight: 1570,
    lastMaintenanceDate: '11/2024',
    lastServiceKm: 35000,
    doors: 4, seats: 5,
    bodyType: 'Berline',
  },
];

for (const s of specs) {
  if (!s.id) { console.log('⚠️ Not found:', s); continue; }
  const fields = Object.entries(s).filter(([k]) => k !== 'id');
  const setClauses = fields.map(([k]) => `${k}=?`).join(',');
  const values = fields.map(([, v]) => v);
  await c.execute({ sql: `UPDATE listings SET ${setClauses} WHERE id=?`, args: [...values, s.id] });
  console.log('✅ Updated:', s.id);
}
console.log('Done!');
